import { site } from "@/config/site";

/**
 * Customer-facing German copy. One place, no JSX. An `/en` tree later adds
 * `src/content/en/copy.ts` with the same shape.
 */
export const copy = {
  nav: {
    evenings: "Abende",
    atelier: "Das Atelier",
    privateEvents: "Private Events",
    faq: "FAQ",
    cta: "Platz sichern",
    menuOpen: "Menü öffnen",
    menuClose: "Menü schließen",
    skip: "Zum Inhalt springen",
    mobileSticky: "Nächsten Abend ansehen",
  },
  cta: {
    chooseEvening: "Abend auswählen",
    secureSeat: "Platz sichern",
    details: "Details ansehen",
    waitlist: "Auf die Warteliste",
    privateInquiry: "Einen eigenen Abend anfragen",
    experience: "Das Erlebnis",
    allEvenings: "Alle Abende",
    openRoute: "Route öffnen",
    follow: `@${site.social.instagramHandle} folgen`,
    notify: "Benachrichtigt mich",
    share: "Freunden schicken",
    calendar: "Zum Kalender hinzufügen",
    back: "Zurück",
  },
  hero: {
    eyebrow: "Paint & Drink · Bayreuth",
    headline: ["Ein Abend,", "den du mit nach", "Hause nimmst."],
    sub: "20 Plätze an einem langen Tisch. Leinwand, Farben und ein Welcome Drink inklusive. Das Bild gehört dir.",
    location: `${site.address.city} · ${site.address.street}`,
    nextLabel: "Nächster Abend",
  },
  proposition: {
    lines: ["20 Menschen.", "20 Leinwände.", "Ein Abend, den niemand", "pünktlich beendet."],
    aside: "Du kommst wegen des Abends. Das Bild nimmst du mit.",
    rarity: "Nur wenige Abende im Monat.",
  },
  nextEvent: {
    eyebrow: "Der nächste Abend",
    doors: "Einlass",
    start: "Beginn",
    end: "Ende",
    price: "pro Person",
    priceNote: "inkl. MwSt.",
    includedTitle: "Im Ticket enthalten",
    soldOut: "Ausverkauft",
    age: (age: number) => `Ab ${age} Jahren`,
    salesSoon: "Verkauf startet bald",
    noEvents: "Die nächsten Termine werden gerade geplant.",
    noEventsSub: "Trag dich ein, und wir sagen dir zuerst Bescheid.",
  },
  inclusions: {
    eyebrow: "Was ein Platz bedeutet",
    headline: "Alles steht bereit, wenn du kommst.",
    items: [
      { title: "Deine Leinwand", text: "Grundiert, auf der Staffelei. Sie wartet auf dich." },
      { title: "Farben & Pinsel", text: "Acryl in sorgfältig gewählten Tönen. Pinsel in drei Stärken." },
      { title: "Schürze & Staffelei", text: "Du kommst, wie du bist. Wir kümmern uns um den Rest." },
      { title: "Welcome Drink", text: "Ein Glas zur Begrüßung ist inklusive. Weitere gibt es an der Bar." },
      { title: "Die ganze Session", text: "Rund drei Stunden, geführt und doch frei. Ohne Noten, ohne Vorwissen." },
      { title: "Dein Bild", text: "Du nimmst es mit. Trocken genug, versprochen." },
    ],
  },
  evening: {
    eyebrow: "Der Abend",
    headline: "So läuft es ab.",
    steps: [
      { time: "Einlass", title: "Ankommen", text: "Die Tür ist offen, der Tisch gedeckt. Du suchst dir deinen Platz." },
      { time: "Erste Minuten", title: "Welcome Drink", text: "Ein Glas, ein Blick in die Runde. Das Motiv des Abends steht vorne." },
      { time: "Erste Stunde", title: "Die Leinwand", text: "Schritt für Schritt. Wer hängt, bekommt Hilfe. Wer abweicht, darf das." },
      { time: "Zwischendurch", title: "Gespräche", text: "Die Musik wird etwas lauter, die Pinsel langsamer. Niemand hat es eilig." },
      { time: "Letzte Stunde", title: "Letzte Striche", text: "Signatur unten rechts. Oder links. Ganz wie du willst." },
      { time: "Ende", title: "Mit nach Hause", text: "Dein Bild, eingepackt. Der Abend bleibt." },
    ],
  },
  gallery: {
    eyebrow: "Das Atelier",
    headline: "Ein langer Tisch in der Schulstraße.",
    text: "Warmes Licht, offene Flaschen, zwanzig Leinwände. Was hier entsteht, sieht jeden Abend anders aus.",
  },
  upcoming: {
    eyebrow: "Kommende Abende",
    headline: "Wenige Termine. Mit Absicht.",
    sub: "Wir öffnen die Türen nur an ausgewählten Abenden. So bleibt es, was es sein soll: ein kleiner Kreis.",
    empty: "Gerade ist kein Abend geöffnet.",
    emptySub: "Die nächsten Termine kommen bald. Trag dich ein, dann erfährst du es zuerst.",
    states: {
      available: "Verfügbar",
      low: "Wenige Plätze",
      few: "Fast ausgebucht",
      sold_out: "Ausverkauft",
      coming_soon: "Bald",
      closed: "Verkauf beendet",
      past: "Vorbei",
    },
  },
  privateNights: {
    eyebrow: "Private Events",
    headline: "Der Tisch, nur für euch.",
    text: "Geburtstag, JGA, Teamabend oder einfach ein Anlass, der mehr verdient als ein Restaurant. Wir öffnen das Atelier für eure Gruppe – mit eigenem Motiv, eigener Musik, eigenem Tempo.",
    cases: ["JGA", "Geburtstag", "Teamabend", "Private Feier"],
  },
  instagram: {
    eyebrow: "Instagram",
    headline: "Was zuletzt entstanden ist.",
  },
  location: {
    eyebrow: "Wo",
    headline: "Mitten in Bayreuth.",
    text: "Schulstraße 1, ein paar Schritte von der Fußgängerzone. Zu Fuß, mit dem Rad oder mit dem Bus gut erreichbar.",
  },
  faq: {
    eyebrow: "Fragen",
    headline: "Was du wissen willst.",
  },
  finalCta: {
    headline: ["Paint", "the night."],
    sub: "Der nächste Abend wartet.",
  },
  social: {
    eyebrow: "Stimmen",
    emptyTitle: "Die ersten Abende stehen noch bevor.",
    emptyText: "Sobald Gäste ihre Bilder mit nach Hause genommen haben, lesen Sie hier, was sie erlebt haben.",
  },
  footer: {
    legal: { impressum: "Impressum", datenschutz: "Datenschutz", agb: "Ticketbedingungen", cookies: "Cookie-Einstellungen", contact: "Kontakt" },
    explore: { events: "Abende", atelier: "Das Atelier", privateEvents: "Private Events", voucher: "Gutschein", faq: "FAQ" },
    // Getter: Workers freeze the clock at epoch during module init, so the year must be read per access.
    get company() {
      return `© ${new Date().getFullYear()} ${site.company.legalName}`;
    },
    line: "Paint & Drink in Bayreuth.",
  },
  event: {
    breadcrumbHome: "Start",
    breadcrumbEvents: "Abende",
    doors: "Einlass",
    time: "Uhrzeit",
    place: "Ort",
    price: "Preis",
    priceVat: "inkl. MwSt.",
    seats: "Plätze",
    age: "Alter",
    ageLine: (age: number) => `Ab ${age} Jahren. Der Ausweis wird vor Ort kontrolliert.`,
    included: "Inklusive",
    about: "Der Abend",
    quantity: "Anzahl",
    perPerson: "pro Person",
    total: "Gesamt",
    buy: "Zur Buchung",
    waitlist: "Auf die Warteliste",
    soldOut: "Ausverkauft",
    salesSoon: "Der Verkauf hat noch nicht begonnen.",
    salesClosed: "Der Verkauf für diesen Abend ist beendet.",
    preLaunch: "Der Ticketverkauf startet in Kürze.",
    preLaunchSub: "Trag dich ein, und wir sagen dir zuerst Bescheid.",
    maxReached: (max: number) => `Maximal ${max} Tickets pro Buchung.`,
    onlyLeft: (n: number) => (n === 1 ? "Nur noch 1 Platz verfügbar." : `Nur noch ${n} Plätze verfügbar.`),
    share: "Teilen",
    accessibility: "Fragen zur Barrierefreiheit? Schreib uns vorab, wir finden eine Lösung.",
    policiesTitle: "Gut zu wissen",
  },
  checkout: {
    eyebrow: "Buchung",
    headline: "Fast da.",
    customer: "Deine Daten",
    firstName: "Vorname",
    lastName: "Nachname",
    email: "E-Mail",
    emailHint: "Hierhin schicken wir deine Tickets.",
    quantity: "Tickets",
    summary: "Zusammenfassung",
    terms: "Ich habe die Ticketbedingungen gelesen und akzeptiere sie.",
    termsLink: "Ticketbedingungen",
    privacyNote: "Informationen zur Verarbeitung deiner Daten findest du in der Datenschutzerklärung.",
    privacyLink: "Datenschutzerklärung",
    marketing: "Ich möchte gelegentlich von neuen Abenden erfahren. Abmeldung jederzeit möglich.",
    pay: "Zahlungspflichtig buchen",
    payNote: "Du wirst zur sicheren Bezahlung an Stripe weitergeleitet.",
    holdNote: (min: number) => `Deine Plätze sind für ${min} Minuten reserviert.`,
    ageNote: (age: number) => `Teilnahme ab ${age} Jahren. Der Ausweis wird vor Ort kontrolliert.`,
    cancellationTitle: "Stornierung",
    errors: {
      generic: "Das hat leider nicht geklappt. Bitte versuche es noch einmal.",
      capacity: (n: number) => (n === 0 ? "Dieser Abend ist inzwischen ausverkauft." : `Es sind nur noch ${n} ${n === 1 ? "Platz" : "Plätze"} verfügbar.`),
      salesDisabled: "Der Ticketverkauf ist noch nicht freigeschaltet.",
      terms: "Bitte akzeptiere die Ticketbedingungen.",
      email: "Bitte gib eine gültige E-Mail-Adresse an.",
      required: "Bitte ausfüllen.",
    },
  },
  success: {
    headline: "Dein Platz ist reserviert.",
    pendingHeadline: "Einen Moment.",
    pendingText: "Wir bestätigen gerade deine Zahlung. Die Seite aktualisiert sich automatisch.",
    sub: (n: number) => (n === 1 ? "Wir freuen uns auf dich." : "Wir freuen uns auf euch."),
    emailNote: (email: string) => `Deine Bestätigung ist unterwegs an ${email}.`,
    reference: "Referenz",
    tickets: "Tickets",
    arrival: "Einlass ab",
    venue: "Ort",
    reviewHeadline: "Fast.",
    reviewText: "Deine Zahlung ist eingegangen, aber der Abend war in der Zwischenzeit ausgebucht. Wir melden uns innerhalb eines Werktags persönlich bei dir und erstatten den Betrag, falls wir keinen Platz finden.",
  },
  cancelled: {
    headline: "Kein Problem.",
    text: "Die Zahlung wurde abgebrochen, es wurde nichts berechnet. Deine Plätze sind wieder frei – wenn du magst, versuch es einfach noch einmal.",
    cta: "Zurück zum Abend",
  },
  waitlist: {
    eyebrow: "Warteliste",
    headline: "Wir sagen dir Bescheid.",
    text: "Wird ein Platz frei oder öffnet ein neuer Abend, bekommst du eine E-Mail. Keine Zahlung, keine Verpflichtung.",
    name: "Name",
    email: "E-Mail",
    quantity: "Gewünschte Plätze",
    event: "Abend",
    anyEvent: "Nächster freier Abend",
    submit: "Eintragen",
    successTitle: "Du stehst auf der Liste.",
    successText: "Sobald sich etwas tut, hörst du von uns.",
    alreadyTitle: "Du stehst bereits auf der Liste.",
    alreadyText: "Wir haben deine E-Mail-Adresse schon notiert. Du hörst von uns.",
  },
  privateForm: {
    headline: "Erzähl uns von eurem Abend.",
    text: "Wir melden uns innerhalb von zwei Werktagen mit einem Vorschlag.",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon (optional)",
    type: "Art des Abends",
    types: ["JGA", "Geburtstag", "Teamevent", "Private Feier", "Etwas anderes"],
    guests: "Ungefähre Gästezahl",
    date: "Wunschtermin",
    altDate: "Alternativtermin (optional)",
    message: "Was sollen wir wissen?",
    submit: "Anfrage senden",
    successTitle: "Danke. Wir melden uns.",
    successText: "Deine Anfrage ist angekommen. Du bekommst gleich eine Bestätigung per E-Mail.",
  },
  voucher: {
    eyebrow: "Gutschein",
    headline: "Ein Abend, verschenkt.",
    text: "Bald kannst du hier einen Gutschein für einen Platz im Atelier kaufen. Bis dahin: schreib uns, wir finden eine Lösung.",
    soon: "Bald verfügbar",
  },
  contact: {
    eyebrow: "Kontakt",
    headline: "Schreib uns.",
    text: "Für Fragen zu Abenden, Tickets oder privaten Anlässen. Wir antworten in der Regel innerhalb eines Werktags.",
  },
  errors: {
    notFoundTitle: "Diese Seite gibt es nicht.",
    notFoundText: "Vielleicht ist der Abend vorbei, vielleicht hat sich der Link vertippt.",
    notFoundCta: "Zur Startseite",
    genericTitle: "Etwas ist schiefgelaufen.",
    genericText: "Das lag an uns, nicht an dir. Bitte versuche es in einem Moment noch einmal.",
    retry: "Noch einmal versuchen",
    networkTitle: "Keine Verbindung.",
    networkText: "Bitte prüfe dein Netz und lade die Seite neu.",
  },
} as const;

export type Copy = typeof copy;
export const getCopy = () => copy;
